# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45481da784f2d5aef5b8a437006f3d53bee8ea67e799cde83704a5c3642fbd58f13129f901326c4d2ad2d412b85cf409c59285168551ac10dcdd1c1072ef3bfc

test:
  secret_key_base: d3bef8835880b90714441884d017ebb8a087d9e0bb0766bd2134dfd873fc9d75f17dd697adb79dc872cd8e4da8b707ea3e355aec9bda50bea42e79e97d987e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
