# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Commune.create([
	{name: 'ALGARROBO'},
	{ name: 'ALHUE'},
	{ name: 'ALTO BIOBIO'},
	{ name: 'ALTO DEL CARMEN'},
	{ name: 'ALTO HOSPICIO'},
	{ name: 'ANCUD'},
	{ name: 'ANDACOLLO'},
	{ name: 'ANGOL'},
	{ name: 'ANTOFAGASTA'},
	{ name: 'ANTUCO'},
	{ name: 'ARAUCO'},
	{ name: 'ARICA'},
	{ name: 'AYSEN'},
	{ name: 'BUIN'},
	{ name: 'BULNES'},
	{ name: 'CABILDO'},
	{ name: 'CABO DE HORNOS'},
	{ name: 'CABRERO'},
	{ name: 'CALAMA'},
	{ name: 'CALBUCO'},
	{ name: 'CALDERA'},
	{ name: 'CALERA DE TANGO'},
	{ name: 'CALLE LARGA'},
	{ name: 'CAMARONES'},
	{ name: 'CAMINA'},
	{ name: 'CANELA'},
	{ name: 'CANETE'},
	{ name: 'CARAHUE'},
	{ name: 'CARTAGENA'},
	{ name: 'CASABLANCA'},
	{ name: 'CASTRO'},
	{ name: 'CATEMU'},
	{ name: 'CAUQUENES'},
	{ name: 'CERRILLOS'},
	{ name: 'CERRO NAVIA'},
	{ name: 'CHAITEN'},
	{ name: 'CHANARAL'},
	{ name: 'CHANCO'},
	{ name: 'CHEPICA'},
	{ name: 'CHIGUAYANTE'},
	{ name: 'CHILE CHICO'},
	{ name: 'CHILLAN'},
	{ name: 'CHILLAN VIEJO'},
	{ name: 'CHIMBARONGO'},
	{ name: 'CHOLCHOL'},
	{ name: 'CHONCHI'},
	{ name: 'CISNES'},
	{ name: 'COBQUECURA'},
	{ name: 'COCHAMO'},
	{ name: 'COCHRANE'},
	{ name: 'CODEGUA'},
	{ name: 'COELEMU'},
	{ name: 'COIHUECO'},
	{ name: 'COINCO'},
	{ name: 'COLBUN'},
	{ name: 'COLCHANE'},
	{ name: 'COLINA'},
	{ name: 'COLLIPULLI'},
	{ name: 'COLTAUCO'},
	{ name: 'COMBARBALA'},
	{ name: 'CONCEPCION'},
	{ name: 'CONCHALI'},
	{ name: 'CONCON'},
	{ name: 'CONSTITUCION'},
	{ name: 'CONTULMO'},
	{ name: 'COPIAPO'},
	{ name: 'COQUIMBO'},
	{ name: 'CORONEL'},
	{ name: 'CORRAL'},
	{ name: 'COYHAIQUE'},
	{ name: 'CUNCO'},
	{ name: 'CURACAUTIN'},
	{ name: 'CURACAVI'},
	{ name: 'CURACO DE VELEZ'},
	{ name: 'CURANILAHUE'},
	{ name: 'CURARREHUE'},
	{ name: 'CUREPTO'},
	{ name: 'CURICO'},
	{ name: 'DALCAHUE'},
	{ name: 'DIEGO DE ALMAGRO'},
	{ name: 'DONIHUE'},
	{ name: 'EL BOSQUE'},
	{ name: 'EL CARMEN'},
	{ name: 'EL MONTE'},
	{ name: 'EL QUISCO'},
	{ name: 'EL TABO'},
	{ name: 'EMPEDRADO'},
	{ name: 'ERCILLA'},
	{ name: 'ESTACION CENTRAL'},
	{ name: 'FLORIDA'},
	{ name: 'FREIRE'},
	{ name: 'FREIRINA'},
	{ name: 'FRESIA'},
	{ name: 'FRUTILLAR'},
	{ name: 'FUTALEUFU'},
	{ name: 'FUTRONO'},
	{ name: 'GALVARINO'},
	{ name: 'GENERAL LAGOS'},
	{ name: 'GORBEA'},
	{ name: 'GRANEROS'},
	{ name: 'GUAITECAS'},
	{ name: 'HIJUELAS'},
	{ name: 'HUALAIHUE'},
	{ name: 'HUALANE'},
	{ name: 'HUALPEN'},
	{ name: 'HUALQUI'},
	{ name: 'HUARA'},
	{ name: 'HUASCO'},
	{ name: 'HUECHURABA'},
	{ name: 'ILLAPEL'},
	{ name: 'INDEPENDENCIA'},
	{ name: 'IQUIQUE'},
	{ name: 'ISLA DE MAIPO'},
	{ name: 'ISLA DE PASCUA'},
	{ name: 'JUAN FERNANDEZ'},
	{ name: 'LA CALERA'},
	{ name: 'LA CISTERNA'},
	{ name: 'LA CRUZ'},
	{ name: 'LA ESTRELLA'},
	{ name: 'LA FLORIDA'},
	{ name: 'LA GRANJA'},
	{ name: 'LA HIGUERA'},
	{ name: 'LA LIGUA'},
	{ name: 'LA PINTANA'},
	{ name: 'LA REINA'},
	{ name: 'LA SERENA'},
	{ name: 'LA UNION'},
	{ name: 'LAGO RANCO'},
	{ name: 'LAGO VERDE'},
	{ name: 'LAGUNA BLANCA'},
	{ name: 'LAJA'},
	{ name: 'LAMPA'},
	{ name: 'LANCO'},
	{ name: 'LAS CABRAS'},
	{ name: 'LAS CONDES'},
	{ name: 'LAUTARO'},
	{ name: 'LEBU'},
	{ name: 'LICANTEN'},
	{ name: 'LIMACHE'},
	{ name: 'LINARES'},
	{ name: 'LITUECHE'},
	{ name: 'LLANQUIHUE'},
	{ name: 'LLAY-LLAY'},
	{ name: 'LO BARNECHEA'},
	{ name: 'LO ESPEJO'},
	{ name: 'LO PRADO'},
	{ name: 'LOLOL'},
	{ name: 'LONCOCHE'},
	{ name: 'LONGAVI'},
	{ name: 'LONQUIMAY'},
	{ name: 'LOS ALAMOS'},
	{ name: 'LOS ANDES'},
	{ name: 'LOS ANGELES'},
	{ name: 'LOS LAGOS'},
	{ name: 'LOS MUERMOS'},
	{ name: 'LOS SAUCES'},
	{ name: 'LOS VILOS'},
	{ name: 'LOTA'},
	{ name: 'LUMACO'},
	{ name: 'MACHALI'},
	{ name: 'MACUL'},
	{ name: 'MAFIL'},
	{ name: 'MAIPU'},
	{ name: 'MALLOA'},
	{ name: 'MARCHIGUE'},
	{ name: 'MARIA ELENA'},
	{ name: 'MARIA PINTO'},
	{ name: 'MARIQUINA'},
	{ name: 'MAULE'},
	{ name: 'MAULLIN'},
	{ name: 'MEJILLONES'},
	{ name: 'MELIPEUCO'},
	{ name: 'MELIPILLA'},
	{ name: 'MOLINA'},
	{ name: 'MONTE PATRIA'},
	{ name: 'MULCHEN'},
	{ name: 'NACIMIENTO'},
	{ name: 'NANCAGUA'},
	{ name: 'NATALES'},
	{ name: 'NAVIDAD'},
	{ name: 'NEGRETE'},
	{ name: 'NINHUE'},
	{ name: 'NIQUEN'},
	{ name: 'NOGALES'},
	{ name: 'NUEVA IMPERIAL'},
	{ name: 'NUNOA'},
	{ name: 'OHIGGINS'},
	{ name: 'OLIVAR'},
	{ name: 'OLLAGUE'},
	{ name: 'OLMUE'},
	{ name: 'OSORNO'},
	{ name: 'OVALLE'},
	{ name: 'PADRE HURTADO'},
	{ name: 'PADRE LAS CASAS'},
	{ name: 'PAIHUANO'},
	{ name: 'PAILLACO'},
	{ name: 'PAINE'},
	{ name: 'PALENA'},
	{ name: 'PALMILLA'},
	{ name: 'PANGUIPULLI'},
	{ name: 'PANQUEHUE'},
	{ name: 'PAPUDO'},
	{ name: 'PAREDONES'},
	{ name: 'PARRAL'},
	{ name: 'PEDRO AGUIRRE CERDA'},
	{ name: 'PELARCO'},
	{ name: 'PELLUHUE'},
	{ name: 'PEMUCO'},
	{ name: 'PENAFLOR'},
	{ name: 'PENALOLEN'},
	{ name: 'PENCAHUE'},
	{ name: 'PENCO'},
	{ name: 'PERALILLO'},
	{ name: 'PERQUENCO'},
	{ name: 'PETORCA'},
	{ name: 'PEUMO'},
	{ name: 'PICA'},
	{ name: 'PICHIDEGUA'},
	{ name: 'PICHILEMU'},
	{ name: 'PINTO'},
	{ name: 'PIRQUE'},
	{ name: 'PITRUFQUEN'},
	{ name: 'PLACILLA'},
	{ name: 'PORTEZUELO'},
	{ name: 'PORVENIR'},
	{ name: 'POZO ALMONTE'},
	{ name: 'PRIMAVERA'},
	{ name: 'PROVIDENCIA'},
	{ name: 'PUCHUNCAVI'},
	{ name: 'PUCON'},
	{ name: 'PUDAHUEL'},
	{ name: 'PUENTE ALTO'},
	{ name: 'PUERTO MONTT'},
	{ name: 'PUERTO OCTAY'},
	{ name: 'PUERTO VARAS'},
	{ name: 'PUMANQUE'},
	{ name: 'PUNITAQUI'},
	{ name: 'PUNTA ARENAS'},
	{ name: 'PUQUELDON'},
	{ name: 'PUREN'},
	{ name: 'PURRANQUE'},
	{ name: 'PUTAENDO'},
	{ name: 'PUTRE'},
	{ name: 'PUYEHUE'},
	{ name: 'QUEILEN'},
	{ name: 'QUELLON'},
	{ name: 'QUEMCHI'},
	{ name: 'QUILACO'},
	{ name: 'QUILICURA'},
	{ name: 'QUILLECO'},
	{ name: 'QUILLON'},
	{ name: 'QUILLOTA'},
	{ name: 'QUILPUE'},
	{ name: 'QUINCHAO'},
	{ name: 'QUINTA DE TILCOCO'},
	{ name: 'QUINTA NORMAL'},
	{ name: 'QUINTERO'},
	{ name: 'QUIRIHUE'},
	{ name: 'RANCAGUA'},
	{ name: 'RANQUIL'},
	{ name: 'RAUCO'},
	{ name: 'RECOLETA'},
	{ name: 'RENAICO'},
	{ name: 'RENCA'},
	{ name: 'RENGO'},
	{ name: 'REQUINOA'},
	{ name: 'RETIRO'},
	{ name: 'RINCONADA'},
	{ name: 'RIO BUENO'},
	{ name: 'RIO CLARO'},
	{ name: 'RIO HURTADO'},
	{ name: 'RIO IBANEZ'},
	{ name: 'RIO NEGRO'},
	{ name: 'RIO VERDE'},
	{ name: 'ROMERAL'},
	{ name: 'SAAVEDRA'},
	{ name: 'SAGRADA FAMILIA'},
	{ name: 'SALAMANCA'},
	{ name: 'SAN ANTONIO'},
	{ name: 'SAN BERNARDO'},
	{ name: 'SAN CARLOS'},
	{ name: 'SAN CLEMENTE'},
	{ name: 'SAN ESTEBAN'},
	{ name: 'SAN FABIAN'},
	{ name: 'SAN FELIPE'},
	{ name: 'SAN FERNANDO'},
	{ name: 'SAN FRANCISCO DE MOSTAZAL'},
	{ name: 'SAN GREGORIO'},
	{ name: 'SAN IGNACIO'},
	{ name: 'SAN JAVIER'},
	{ name: 'SAN JOAQUIN'},
	{ name: 'SAN JOSE DE MAIPO'},
	{ name: 'SAN JUAN DE LA COSTA'},
	{ name: 'SAN MIGUEL'},
	{ name: 'SAN NICOLAS'},
	{ name: 'SAN PABLO'},
	{ name: 'SAN PEDRO'},
	{ name: 'SAN PEDRO DE ATACAMA'},
	{ name: 'SAN PEDRO DE LA PAZ'},
	{ name: 'SAN RAFAEL'},
	{ name: 'SAN RAMON'},
	{ name: 'SAN ROSENDO'},
	{ name: 'SAN VICENTE'},
	{ name: 'SANTA BARBARA'},
	{ name: 'SANTA CRUZ'},
	{ name: 'SANTA JUANA'},
	{ name: 'SANTA MARIA'},
	{ name: 'SANTIAGO'},
	{ name: 'SANTIAGO OESTE'},
	{ name: 'SANTIAGO SUR'},
	{ name: 'SANTO DOMINGO'},
	{ name: 'SIERRA GORDA'},
	{ name: 'TALAGANTE'},
	{ name: 'TALCA'},
	{ name: 'TALCAHUANO'},
	{ name: 'TALTAL'},
	{ name: 'TEMUCO'},
	{ name: 'TENO'},
	{ name: 'TEODORO SCHMIDT'},
	{ name: 'TIERRA AMARILLA'},
	{ name: 'TIL-TIL'},
	{ name: 'TIMAUKEL'},
	{ name: 'TIRUA'},
	{ name: 'TOCOPILLA'},
	{ name: 'TOLTEN'},
	{ name: 'TOME'},
	{ name: 'TORRES DEL PAINE'},
	{ name: 'TORTEL'},
	{ name: 'TRAIGUEN'},
	{ name: 'TREHUACO'},
	{ name: 'TUCAPEL'},
	{ name: 'VALDIVIA'},
	{ name: 'VALLENAR'},
	{ name: 'VALPARAISO'},
	{ name: 'VICHUQUEN'},
	{ name: 'VICTORIA'},
	{ name: 'VICUNA'},
	{ name: 'VILCUN'},
	{ name: 'VILLA ALEGRE'},
	{ name: 'VILLA ALEMANA'},
	{ name: 'VILLARRICA'},
	{ name: 'VINA DEL MAR'},
	{ name: 'VITACURA'},
	{ name: 'YERBAS BUENAS'},
	{ name: 'YUMBEL'},
	{ name: 'YUNGAY'},
	{ name: 'ZAPALLAR'}])