# This File Should Contain All The Record Creation Needed To Seed The Database With Its Default Values.
# The Data Can Then Be Loaded With The Rails Db:seed Command (or Created Alongside The Database With Db:setup).
#
# Examples:
#
#   Movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord Of The Rings' }])
#   Character.create(name: 'luke', Movie: Movies.first)

Commune.create([
	{ name: 'Algarrobo'},
	{ name: 'Alhue'},
	{ name: 'Alto Biobio'},
	{ name: 'Alto Del Carmen'},
	{ name: 'Alto Hospicio'},
	{ name: 'Ancud'},
	{ name: 'Andacollo'},
	{ name: 'Angol'},
	{ name: 'Antofagasta'},
	{ name: 'Antuco'},
	{ name: 'Arauco'},
	{ name: 'Arica'},
	{ name: 'Aysen'},
	{ name: 'Buin'},
	{ name: 'Bulnes'},
	{ name: 'Cabildo'},
	{ name: 'Cabo De Hornos'},
	{ name: 'Cabrero'},
	{ name: 'Calama'},
	{ name: 'Calbuco'},
	{ name: 'Caldera'},
	{ name: 'Calera De Tango'},
	{ name: 'Calle Larga'},
	{ name: 'Camarones'},
	{ name: 'Camina'},
	{ name: 'Canela'},
	{ name: 'Canete'},
	{ name: 'Carahue'},
	{ name: 'Cartagena'},
	{ name: 'Casablanca'},
	{ name: 'Castro'},
	{ name: 'Catemu'},
	{ name: 'Cauquenes'},
	{ name: 'Cerrillos'},
	{ name: 'Cerro Navia'},
	{ name: 'Chaiten'},
	{ name: 'Chanaral'},
	{ name: 'Chanco'},
	{ name: 'Chepica'},
	{ name: 'Chiguayante'},
	{ name: 'Chile Chico'},
	{ name: 'Chillan'},
	{ name: 'Chillan Viejo'},
	{ name: 'Chimbarongo'},
	{ name: 'Cholchol'},
	{ name: 'Chonchi'},
	{ name: 'Cisnes'},
	{ name: 'Cobquecura'},
	{ name: 'Cochamo'},
	{ name: 'Cochrane'},
	{ name: 'Codegua'},
	{ name: 'Coelemu'},
	{ name: 'Coihueco'},
	{ name: 'Coinco'},
	{ name: 'Colbun'},
	{ name: 'Colchane'},
	{ name: 'Colina'},
	{ name: 'Collipulli'},
	{ name: 'Coltauco'},
	{ name: 'Combarbala'},
	{ name: 'Concepcion'},
	{ name: 'Conchali'},
	{ name: 'Concon'},
	{ name: 'Constitucion'},
	{ name: 'Contulmo'},
	{ name: 'Copiapo'},
	{ name: 'Coquimbo'},
	{ name: 'Coronel'},
	{ name: 'Corral'},
	{ name: 'Coyhaique'},
	{ name: 'Cunco'},
	{ name: 'Curacautin'},
	{ name: 'Curacavi'},
	{ name: 'Curaco De Velez'},
	{ name: 'Curanilahue'},
	{ name: 'Curarrehue'},
	{ name: 'Curepto'},
	{ name: 'Curico'},
	{ name: 'Dalcahue'},
	{ name: 'Diego De Almagro'},
	{ name: 'Donihue'},
	{ name: 'El Bosque'},
	{ name: 'El Carmen'},
	{ name: 'El Monte'},
	{ name: 'El Quisco'},
	{ name: 'El Tabo'},
	{ name: 'Empedrado'},
	{ name: 'Ercilla'},
	{ name: 'Estacion Central'},
	{ name: 'Florida'},
	{ name: 'Freire'},
	{ name: 'Freirina'},
	{ name: 'Fresia'},
	{ name: 'Frutillar'},
	{ name: 'Futaleufu'},
	{ name: 'Futrono'},
	{ name: 'Galvarino'},
	{ name: 'General Lagos'},
	{ name: 'Gorbea'},
	{ name: 'Graneros'},
	{ name: 'Guaitecas'},
	{ name: 'Hijuelas'},
	{ name: 'Hualaihue'},
	{ name: 'Hualane'},
	{ name: 'Hualpen'},
	{ name: 'Hualqui'},
	{ name: 'Huara'},
	{ name: 'Huasco'},
	{ name: 'Huechuraba'},
	{ name: 'Illapel'},
	{ name: 'Independencia'},
	{ name: 'Iquique'},
	{ name: 'Isla De Maipo'},
	{ name: 'Isla De Pascua'},
	{ name: 'Juan Fernandez'},
	{ name: 'La Calera'},
	{ name: 'La Cisterna'},
	{ name: 'La Cruz'},
	{ name: 'La Estrella'},
	{ name: 'La Florida'},
	{ name: 'La Granja'},
	{ name: 'La Higuera'},
	{ name: 'La Ligua'},
	{ name: 'La Pintana'},
	{ name: 'La Reina'},
	{ name: 'La Serena'},
	{ name: 'La Union'},
	{ name: 'Lago Ranco'},
	{ name: 'Lago Verde'},
	{ name: 'Laguna Blanca'},
	{ name: 'Laja'},
	{ name: 'Lampa'},
	{ name: 'Lanco'},
	{ name: 'Las Cabras'},
	{ name: 'Las Condes'},
	{ name: 'Lautaro'},
	{ name: 'Lebu'},
	{ name: 'Licanten'},
	{ name: 'Limache'},
	{ name: 'Linares'},
	{ name: 'Litueche'},
	{ name: 'Llanquihue'},
	{ name: 'Llay-llay'},
	{ name: 'Lo Barnechea'},
	{ name: 'Lo Espejo'},
	{ name: 'Lo Prado'},
	{ name: 'Lolol'},
	{ name: 'Loncoche'},
	{ name: 'Longavi'},
	{ name: 'Lonquimay'},
	{ name: 'Los Alamos'},
	{ name: 'Los Andes'},
	{ name: 'Los Angeles'},
	{ name: 'Los Lagos'},
	{ name: 'Los Muermos'},
	{ name: 'Los Sauces'},
	{ name: 'Los Vilos'},
	{ name: 'Lota'},
	{ name: 'Lumaco'},
	{ name: 'Machali'},
	{ name: 'Macul'},
	{ name: 'Mafil'},
	{ name: 'Maipu'},
	{ name: 'Malloa'},
	{ name: 'Marchigue'},
	{ name: 'Maria Elena'},
	{ name: 'Maria Pinto'},
	{ name: 'Mariquina'},
	{ name: 'Maule'},
	{ name: 'Maullin'},
	{ name: 'Mejillones'},
	{ name: 'Melipeuco'},
	{ name: 'Melipilla'},
	{ name: 'Molina'},
	{ name: 'Monte Patria'},
	{ name: 'Mulchen'},
	{ name: 'Nacimiento'},
	{ name: 'Nancagua'},
	{ name: 'Natales'},
	{ name: 'Navidad'},
	{ name: 'Negrete'},
	{ name: 'Ninhue'},
	{ name: 'Niquen'},
	{ name: 'Nogales'},
	{ name: 'Nueva Imperial'},
	{ name: 'Nunoa'},
	{ name: 'Ohiggins'},
	{ name: 'Olivar'},
	{ name: 'Ollague'},
	{ name: 'Olmue'},
	{ name: 'Osorno'},
	{ name: 'Ovalle'},
	{ name: 'Padre Hurtado'},
	{ name: 'Padre Las Casas'},
	{ name: 'Paihuano'},
	{ name: 'Paillaco'},
	{ name: 'Paine'},
	{ name: 'Palena'},
	{ name: 'Palmilla'},
	{ name: 'Panguipulli'},
	{ name: 'Panquehue'},
	{ name: 'Papudo'},
	{ name: 'Paredones'},
	{ name: 'Parral'},
	{ name: 'Pedro Aguirre Cerda'},
	{ name: 'Pelarco'},
	{ name: 'Pelluhue'},
	{ name: 'Pemuco'},
	{ name: 'Penaflor'},
	{ name: 'Penalolen'},
	{ name: 'Pencahue'},
	{ name: 'Penco'},
	{ name: 'Peralillo'},
	{ name: 'Perquenco'},
	{ name: 'Petorca'},
	{ name: 'Peumo'},
	{ name: 'Pica'},
	{ name: 'Pichidegua'},
	{ name: 'Pichilemu'},
	{ name: 'Pinto'},
	{ name: 'Pirque'},
	{ name: 'Pitrufquen'},
	{ name: 'Placilla'},
	{ name: 'Portezuelo'},
	{ name: 'Porvenir'},
	{ name: 'Pozo Almonte'},
	{ name: 'Primavera'},
	{ name: 'Providencia'},
	{ name: 'Puchuncavi'},
	{ name: 'Pucon'},
	{ name: 'Pudahuel'},
	{ name: 'Puente Alto'},
	{ name: 'Puerto Montt'},
	{ name: 'Puerto Octay'},
	{ name: 'Puerto Varas'},
	{ name: 'Pumanque'},
	{ name: 'Punitaqui'},
	{ name: 'Punta Arenas'},
	{ name: 'Puqueldon'},
	{ name: 'Puren'},
	{ name: 'Purranque'},
	{ name: 'Putaendo'},
	{ name: 'Putre'},
	{ name: 'Puyehue'},
	{ name: 'Queilen'},
	{ name: 'Quellon'},
	{ name: 'Quemchi'},
	{ name: 'Quilaco'},
	{ name: 'Quilicura'},
	{ name: 'Quilleco'},
	{ name: 'Quillon'},
	{ name: 'Quillota'},
	{ name: 'Quilpue'},
	{ name: 'Quinchao'},
	{ name: 'Quinta De Tilcoco'},
	{ name: 'Quinta Normal'},
	{ name: 'Quintero'},
	{ name: 'Quirihue'},
	{ name: 'Rancagua'},
	{ name: 'Ranquil'},
	{ name: 'Rauco'},
	{ name: 'Recoleta'},
	{ name: 'Renaico'},
	{ name: 'Renca'},
	{ name: 'Rengo'},
	{ name: 'Requinoa'},
	{ name: 'Retiro'},
	{ name: 'Rinconada'},
	{ name: 'Rio Bueno'},
	{ name: 'Rio Claro'},
	{ name: 'Rio Hurtado'},
	{ name: 'Rio Ibanez'},
	{ name: 'Rio Negro'},
	{ name: 'Rio Verde'},
	{ name: 'Romeral'},
	{ name: 'Saavedra'},
	{ name: 'Sagrada Familia'},
	{ name: 'Salamanca'},
	{ name: 'San Antonio'},
	{ name: 'San Bernardo'},
	{ name: 'San Carlos'},
	{ name: 'San Clemente'},
	{ name: 'San Esteban'},
	{ name: 'San Fabian'},
	{ name: 'San Felipe'},
	{ name: 'San Fernando'},
	{ name: 'San Francisco De Mostazal'},
	{ name: 'San Gregorio'},
	{ name: 'San Ignacio'},
	{ name: 'San Javier'},
	{ name: 'San Joaquin'},
	{ name: 'San Jose De Maipo'},
	{ name: 'San Juan De La Costa'},
	{ name: 'San Miguel'},
	{ name: 'San Nicolas'},
	{ name: 'San Pablo'},
	{ name: 'San Pedro'},
	{ name: 'San Pedro De Atacama'},
	{ name: 'San Pedro De La Paz'},
	{ name: 'San Rafael'},
	{ name: 'San Ramon'},
	{ name: 'San Rosendo'},
	{ name: 'San Vicente'},
	{ name: 'Santa Barbara'},
	{ name: 'Santa Cruz'},
	{ name: 'Santa Juana'},
	{ name: 'Santa Maria'},
	{ name: 'Santiago'},
	{ name: 'Santiago Oeste'},
	{ name: 'Santiago Sur'},
	{ name: 'Santo Domingo'},
	{ name: 'Sierra Gorda'},
	{ name: 'Talagante'},
	{ name: 'Talca'},
	{ name: 'Talcahuano'},
	{ name: 'Taltal'},
	{ name: 'Temuco'},
	{ name: 'Teno'},
	{ name: 'Teodoro Schmidt'},
	{ name: 'Tierra Amarilla'},
	{ name: 'Til-til'},
	{ name: 'Timaukel'},
	{ name: 'Tirua'},
	{ name: 'Tocopilla'},
	{ name: 'Tolten'},
	{ name: 'Tome'},
	{ name: 'Torres Del Paine'},
	{ name: 'Tortel'},
	{ name: 'Traiguen'},
	{ name: 'Trehuaco'},
	{ name: 'Tucapel'},
	{ name: 'Valdivia'},
	{ name: 'Vallenar'},
	{ name: 'Valparaiso'},
	{ name: 'Vichuquen'},
	{ name: 'Victoria'},
	{ name: 'Vicuna'},
	{ name: 'Vilcun'},
	{ name: 'Villa Alegre'},
	{ name: 'Villa Alemana'},
	{ name: 'Villarrica'},
	{ name: 'Vina Del Mar'},
	{ name: 'Vitacura'},
	{ name: 'Yerbas Buenas'},
	{ name: 'Yumbel'},
	{ name: 'Yungay'},
	{ name: 'Zapallar'}])